In [1]:
import numpy as np

In [3]:
# Create a rank 1 array
a= np.array([0,1,2])
print (a)

[0 1 2]


In [5]:
print (a.shape)

(3,)


In [7]:
print(a[0])
print(a[1])
print(a[2])

0
1
2


In [8]:
# Change an element of the array
a[0]= 5
print (a)

[5 1 2]


In [9]:
# Create a rank 2 array
b= np.array([[1,2,3],[4,5,6]])

In [10]:
print (b)

[[1 2 3]
 [4 5 6]]


In [11]:
print(b.shape)

(2, 3)


In [12]:
print (b[0, 0], b[0, 1], b[1, 0])

1 2 4


In [2]:
# Create a 3*3 array of all zeros
a = np.zeros((3,3))
print (a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [3]:
# Create a 2*2 array of all ones
b = np.ones((2,2))
print (b)

[[ 1.  1.]
 [ 1.  1.]]


In [4]:
# Create a 3*3 constant array
c = np.full((3,3),7)
print (c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [5]:
# Create a 3*3 array filled with random values
d = np.random.random((3,3))
print (d)

[[ 0.21433944  0.88628768  0.06089936]
 [ 0.3274579   0.34098022  0.2734014 ]
 [ 0.31518848  0.1063552   0.04722162]]


In [6]:
# Create a 3*3 identity matrix
e = np.eye(3)
print (e)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [7]:
# Convert list to array
f= np.array([2,3,1,0])
print (f)

[2 3 1 0]


In [8]:
# Create an arrays with regularly incrementing values using arang() function
g = np.arange(20)
print (g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
# Note mix of tuple and lists
h = np.array ([[0, 1,2.0],[0,0,0], [1+1j,3.,2.]])
print (h)

[[ 0.+0.j  1.+0.j  2.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]
 [ 1.+1.j  3.+0.j  2.+0.j]]


In [11]:
# Create an array of range with float data type
i = np.arange(1,8, dtype= np.float)
print (i)

[ 1.  2.  3.  4.  5.  6.  7.]


In [12]:
# linspace() will create arrays with a specified number of items which are
#spaced equally between the specified beginning and end values
j = np.linspace(2., 4., 5)
print (j)

[ 2.   2.5  3.   3.5  4. ]


In [13]:
# indices() will create a set of arrays stacked as a one-higher
# dimensioned array, one per dimension with each representing variation in that dimension
k = np.indices((2,2))
print (k)

[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]]


# Basic Slicing

The basic slice syntax is i: j: k, where i is the starting index, j is the stopping index, and k is the step and k is not equal to 0. 
This selects the m elements in the corresponding dimension, with index values i, i + k, ...,i + (m - 1) k where m = q + (r not equal to 0) and q and r are the quotient and the remainder is obtained by dividing j - i by k: j - i = q k + r, so that i + (m - 1) k < j.

In [14]:
x = np.array([5, 6, 7, 8, 9])
x[1:7:2]

array([6, 8])

Negative k makes stepping go toward smaller indices. Negative i and j are interpreted as n + i and n + j where n is the number of elements in the corresponding dimension.

In [16]:
print (x[-2:5])
print (x[-1:1:-1])

[8 9]
[9 8 7]


If n is the number of items in the dimension being sliced. Then if i is not  given then it defaults to 0 for k > 0 and n - 1 for k < 0. If j is not given it defaults to n for k > 0 and -1 for k < 0. If k is not given it defaults to 1. Note that :: is the same as : and means select all indices along this axis.

In [17]:
x[4:]

array([9])

If the number of objects in the selection tuple is less than N, then : is assumed for any subsequent dimensions.

In [18]:
y = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print ("Shape of y: ", x.shape)
y[1:3]

Shape of y:  (5,)


array([[[4],
        [5],
        [6]]])

Ellipsis expand to the number of : objects needed to make a selection tuple of the same length as x.ndim. There may only be a single ellipsis present.

In [19]:
x[...,0]

array(5)

In [20]:
# Create a rank 2 array with shape (3, 4)
a = np.array([[5,6,7,8], [1,2,3,4], [9,10,11,12]])
print ("Array a:", a)

Array a: [[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]


In [21]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print ("Array b:", b)

Array b: [[6 7]
 [2 3]]


A slice of an array is a view into the same data, so modifying itwill modify the original array.

In [22]:
print ( a[0, 1])
b[0, 0] = 77
print (a[0, 1])

6
77


Middle row array can be accessed in two ways. 1) Slices along with integer indexing will result in an arry of lower rank. 2) Using only slices will result in same rank array.

In [23]:
row_r1 = a[1,:]# Rank 1 view of the second row of a
row_r2 = a[1:2,:]# Rank 2 view of the second row of a
print (row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print (row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[1 2 3 4] (4,)
[[1 2 3 4]] (1, 4)


In [24]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print (col_r2, col_r2.shape)

[77  2 10] (3,)
[[77]
 [ 2]
 [10]] (3, 1)


# Advanced Indexing

Integer array indexing allows you to construct random arrays and other arrays.

In [25]:
# An example of integer array indexing.
# The returned array will have shape (2,) and
print (a[[0, 1], [0, 1]])
# The above example of integer array indexing is equivalent to this:
print (np.array([a[0, 0], a[1, 1]]))

[5 2]
[5 2]


In [27]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print (a[[0, 0], [1, 1]])

[77 77]


In [28]:
# Equivalent to the previous integer array indexing example
print (np.array([a[0, 1], a[0, 1]]))

[77 77]


Boolean array indexing: This is useful to pick a random element from an array, which is often used for filtering elements that satisfy a given condition.

In [29]:
a=np.array([[1,2], [3, 4], [5, 6]])

In [30]:
# Find the elements of a that are bigger than 2
print (a > 2)

[[False False]
 [ True  True]
 [ True  True]]


In [31]:
# to get the actual value
print (a[a > 2])

[3 4 5 6]


# Array Math

In [3]:
x=np.array([[1,2],[3,4],[5,6]])
y=np.array([[7,8],[9,10],[11,12]])

In [7]:
# Elementwise sum
print (x+y)

[[ 8 10]
 [12 14]
 [16 18]]


In [8]:
print (np.add(x, y))

[[ 8 10]
 [12 14]
 [16 18]]


In [9]:
# Elementwise difference
print (x-y)

[[-6 -6]
 [-6 -6]
 [-6 -6]]


In [10]:
print (np.subtract(x, y))

[[-6 -6]
 [-6 -6]
 [-6 -6]]


In [11]:
# Elementwise product
print (x*y)

[[ 7 16]
 [27 40]
 [55 72]]


In [12]:
print (np.multiply(x, y))

[[ 7 16]
 [27 40]
 [55 72]]


In [13]:
# Elementwise division
print (x/y)

[[ 0.14285714  0.25      ]
 [ 0.33333333  0.4       ]
 [ 0.45454545  0.5       ]]


In [14]:
print (np.divide(x, y))

[[ 0.14285714  0.25      ]
 [ 0.33333333  0.4       ]
 [ 0.45454545  0.5       ]]


In [15]:
# Elementwise square root
print (np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]
 [ 2.23606798  2.44948974]]


** We can use the “dot” function to calculate inner products of vectors or to multiply matrices or multiply a vector by a matrix. **

In [16]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

a=np.array([9,10])
b=np.array([11, 12])

In [19]:
# Inner product of vectors
print (a.dot(b))

219


In [20]:
print (np.dot(a, b))

219


In [21]:
# Matrix / vector product
print (x.dot(a))

[29 67]


In [22]:
print (np.dot(x, a))

[29 67]


In [23]:
print (x.dot(y))

[[19 22]
 [43 50]]


In [24]:
print (np.dot(x, y))

[[19 22]
 [43 50]]


** Sum function ** 

In [25]:
x = np.array([[1,2],[3,4]])

In [26]:
# Compute sum of all elements
print (np.sum(x))

10


In [27]:
# Compute sum of each column
print (np.sum(x, axis=0))

[4 6]


In [28]:
# Compute sum of each row
print (np.sum(x, axis=1))

[3 7]


** Transpose is one of the common operations often performed on matrix, which can be achieved using the T attribute of an array object. **

In [29]:
x=np.array([[1,2], [3,4]])

In [30]:
print (x)
print (x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [31]:
# Note that taking the transpose of a rank 1 array does nothing:
v=np.array([1,2,3])

In [32]:
print (v)
print (v.T)

[1 2 3]
[1 2 3]


# Broadcasting

Broadcasting enables arithmetic operations to be performed between different shaped arrays.

In [34]:
#create a matrix
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# create a vector
v = np.array([1, 0, 1])

In [35]:
# create an empty matrix with the same shape as a
b = np.empty_like(a)

In [37]:
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(3):
 b[i, :] = a[i, :] + v
print (b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


### Broadcasting for large matrix

In [38]:
# Stack 3 copies of v on top of each other
vv = np.tile(v, (3, 1))
print (vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]]


In [39]:
# Add a and vv elementwise
b = a + vv
print (b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


### Broadcasting using NumPy

In [40]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 0, 1])

In [41]:
# Add v to each row of a using broadcasting
b = a + v
print (b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


## Applications of Broadcasting

In [45]:
# Compute outer product of vectors
# v has shape (3,)
v = np.array([1,2,3])
# w has shape (2,)
w = np.array([4,5]) 
#To compute an outer product, we first reshape v to be a column 
# vector of shape (3, 1); we can then broadcast it against w to yield
#an output of shape (3, 2), which is the outer product of v and w:

print (np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [46]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3],[4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3)
print (x + v)

[[2 4 6]
 [5 7 9]]


In [50]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column
print ((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [51]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same output.
print (x + np.reshape(w,(2,1)))

[[ 5  6  7]
 [ 9 10 11]]


In [52]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3)
print (x * 2)

[[ 2  4  6]
 [ 8 10 12]]


 ## Data Structures
**<font color= "red">  Pandas </font> ** introduces two new data structures to Python – ** Series ** and ** DataFrame **, both of which are built on top of NumPy

## Series
This is a one-dimensional object similar to column in a spreadsheet or SQL table. By default each item will be assigned an index label from 0 to N

In [54]:
import pandas as pd
# creating a series by passing a list of values, and a custom index label. 
# Note that the labeled index reference for each row and it can have duplicate values
s = pd.Series([1,2,3,np.nan,5,6], index=['A','B','C','D','E','F'])
print (s)

A    1.0
B    2.0
C    3.0
D    NaN
E    5.0
F    6.0
dtype: float64


## DataFrame
It is a two-dimensional object similar to a spreadsheet or an SQL table. This is the most commonly used pandas object.

In [55]:
# Creating a pandas dataframe
data = {'Gender': ['F', 'M', 'M'],'Emp_ID': ['E01', 'E02', 'E03'],'Age': [25, 27, 25]}
# We want the order the columns, so lets specify in columns parameter
df = pd.DataFrame(data, columns=['Emp_ID','Gender', 'Age'])
df

Emp_ID Gender  Age
0    E01      F   25
1    E02      M   27
2    E03      M   25

# Reading and Writing Data

In [59]:
# Reading / writing data from csv, text, Excel
# Reading
df=pd.read_csv('mtcars.csv')             # from csv
df=pd.read_csv('mtcars.txt', sep='\t')   # from text file
df=pd.read_excel('mtcars.xlsx') # from Excel

In [ ]:
# reading from multiple sheets of same Excel into different dataframes
xlsx = pd.ExcelFile('file_name.xls')
sheet1_df = pd.read_excel(xlsx, 'Sheet1')
sheet2_df = pd.read_excel(xlsx, 'Sheet2')

## writing

In [ ]:
# index = False parameter will not write the index values, default is True
df.to_csv('Data/mtcars_new.csv', index=False)
df.to_csv('Data/mtcars_new.txt', sep='\t', index=False)
df.to_excel('Data/mtcars_new.xlsx',sheet_name='Sheet1', index = False)

# <font color= "darkblue">Basic Statistics Summary </font>
Pandas has some built-in functions to help us to get better understanding of data using basic statistical summary methods. <br><br>
**<font color= "red"> describe() </font>**- will returns the quick stats such as count, mean, std (standard deviation), min, first quartile, median, third quartile, max on each column of the dataframe

In [61]:
df = pd.read_csv('data/iris.csv')
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

**<font color= "red">cov() </font>**- Covariance indicates how two variables are related. A positive covariance means the variables are positively related, while a negative covariance means the variables are inversely related. Drawback of covariance is that it does not tell you the degree of positive or negative relation 

In [62]:
df.cov()

sepal_length  sepal_width  petal_length  petal_width
sepal_length      0.685694    -0.039268      1.273682     0.516904
sepal_width      -0.039268     0.188004     -0.321713    -0.117981
petal_length      1.273682    -0.321713      3.113179     1.296387
petal_width       0.516904    -0.117981      1.296387     0.582414

**<font color= "red">corr() </font>**-Correlation is another way to determine how two variables are related. In addition to telling you whether variables are positively or inversely related, correlation also tells you the degree to which the
variables tend to move together. When you say that two items correlate, you are saying that the change in one item effects a change in another item. You will always talk about correlation as a range between -1 and 1. In the below
example code, petal length is 87% positively related to sepal length that means a change in petal length results in a positive 87% change to sepal lenth and vice versa.

In [63]:
# Creating correlation matrix on dataframe
df.corr()

sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.109369      0.871754     0.817954
sepal_width      -0.109369     1.000000     -0.420516    -0.356544
petal_length      0.871754    -0.420516      1.000000     0.962757
petal_width       0.817954    -0.356544      0.962757     1.000000

# Merge/Join

In [64]:
# Concat or append operation
data = {
        'emp_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Jason', 'Andy', 'Allen', 'Alice', 'Amy'],
        'last_name': ['Larkin', 'Jacob', 'A', 'AA', 'Jackson']}
df_1 = pd.DataFrame(data, columns = ['emp_id', 'first_name', 'last_name'])
data = {
        'emp_id': ['4', '5', '6', '7'],
        'first_name': ['Brian', 'Shize', 'Kim', 'Jose'],
        'last_name': ['Alexander', 'Suma', 'Mike', 'G']}
df_2 = pd.DataFrame(data, columns = ['emp_id', 'first_name', 'last_name'])

In [66]:
#Using concat
df = pd.concat([df_1, df_2])
print (df)

  emp_id first_name  last_name
0      1      Jason     Larkin
1      2       Andy      Jacob
2      3      Allen          A
3      4      Alice         AA
4      5        Amy    Jackson
0      4      Brian  Alexander
1      5      Shize       Suma
2      6        Kim       Mike
3      7       Jose          G


In [67]:
# Using append
print (df_1.append(df_2))

  emp_id first_name  last_name
0      1      Jason     Larkin
1      2       Andy      Jacob
2      3      Allen          A
3      4      Alice         AA
4      5        Amy    Jackson
0      4      Brian  Alexander
1      5      Shize       Suma
2      6        Kim       Mike
3      7       Jose          G


In [68]:
# Join the two dataframes along columns
pd.concat([df_1, df_2], axis=1)

emp_id first_name last_name emp_id first_name  last_name
0      1      Jason    Larkin      4      Brian  Alexander
1      2       Andy     Jacob      5      Shize       Suma
2      3      Allen         A      6        Kim       Mike
3      4      Alice        AA      7       Jose          G
4      5        Amy   Jackson    NaN        NaN        NaN

## Merge two dataframes

In [69]:
# Merge two dataframes based on the emp_id value
# in this case only the emp_id's present in both table will be joined
pd.merge(df_1, df_2, on='emp_id')

emp_id first_name_x last_name_x first_name_y last_name_y
0      4        Alice          AA        Brian   Alexander
1      5          Amy     Jackson        Shize        Suma

# Join

** Left join**  <br>
Left join produces a complete set of records from Table A, with the matching records here available in Table B. If there is no match, the right side will contain null.

In [70]:
# Left join
print (pd.merge(df_1, df_2, on='emp_id', how='left'))

  emp_id first_name_x last_name_x first_name_y last_name_y
0      1        Jason      Larkin          NaN         NaN
1      2         Andy       Jacob          NaN         NaN
2      3        Allen           A          NaN         NaN
3      4        Alice          AA        Brian   Alexander
4      5          Amy     Jackson        Shize        Suma


In [71]:
# Merge while adding a suffix to duplicate column names of both table
print (pd.merge(df_1, df_2, on='emp_id', how='left', suffixes=('_left', '_right')))

  emp_id first_name_left last_name_left first_name_right last_name_right
0      1           Jason         Larkin              NaN             NaN
1      2            Andy          Jacob              NaN             NaN
2      3           Allen              A              NaN             NaN
3      4           Alice             AA            Brian       Alexander
4      5             Amy        Jackson            Shize            Suma


** Right join ** <br>
 Right join produces a complete set of records from Table B, with the matching records where available in Table A. If there is no match, the left side will contain null.

In [73]:
# Right join 
pd.merge(df_1, df_2, on='emp_id', how='right')

emp_id first_name_x last_name_x first_name_y last_name_y
0      4        Alice          AA        Brian   Alexander
1      5          Amy     Jackson        Shize        Suma
2      6          NaN         NaN          Kim        Mike
3      7          NaN         NaN         Jose           G

** Inner Join ** <br>
Inner Join - Inner join produces only the set of records that match in both Table A and Table B.

In [75]:
# Inner join two dataframes
pd.merge(df_1, df_2, on='emp_id', how='inner')

emp_id first_name_x last_name_x first_name_y last_name_y
0      4        Alice          AA        Brian   Alexander
1      5          Amy     Jackson        Shize        Suma

** Outer Join** 
<br>
Full outer join produces the set of all records in Table A and Table B, with matching records from both sides where available. If there is no match, the missing side will contain null

In [76]:
# Outer join two dataframes
pd.merge(df_1, df_2, on='emp_id', how='outer')

emp_id first_name_x last_name_x first_name_y last_name_y
0      1        Jason      Larkin          NaN         NaN
1      2         Andy       Jacob          NaN         NaN
2      3        Allen           A          NaN         NaN
3      4        Alice          AA        Brian   Alexander
4      5          Amy     Jackson        Shize        Suma
5      6          NaN         NaN          Kim        Mike
6      7          NaN         NaN         Jose           G

## Grouping  <br> 
Grouping involves one or more of the following steps:

    • Splitting the data into groups based on some criteria,
    • Applying a function to each group independently,
    • Combining the results into a data structure

In [78]:
# Grouping operation
df = pd.DataFrame({'Name' : ['jack', 'jane', 'jack', 'jane', 'jack', 'jane','jack', 'jane'],
                    'State' : ['SFO', 'SFO', 'NYK', 'CA', 'NYK', 'NYK','SFO', 'CA'],
                   'Grade':['A','A','B','A','C','B','C','A'],
                   'Age' : np.random.uniform(24, 50, size=8),
                   'Salary' : np.random.uniform(3000, 5000, size=8),})

In [79]:
# Note that the columns are ordered automatically in their alphabetic order
df

Age Grade  Name       Salary State
0  30.162886     A  jack  4271.240710   SFO
1  25.589781     A  jane  4731.431501   SFO
2  39.044827     B  jack  3416.599613   NYK
3  26.369079     A  jane  4680.389142    CA
4  26.487404     C  jack  4959.307093   NYK
5  30.523478     B  jane  4901.701010   NYK
6  26.930186     C  jack  4352.625808   SFO
7  42.590085     A  jane  3949.965385    CA

In [81]:
# for custom order please use below code
# df = pd.DataFrame(data, columns = ['Name', 'State', 'Age','Salary'])
# Find max age and salary by Name / State
# with groupby, we can use all aggregate functions such as min, max, mean, count, cumsum
df.groupby(['Name','State']).max()

Age Grade       Salary
Name State                              
jack NYK    39.044827     C  4959.307093
     SFO    30.162886     C  4352.625808
jane CA     42.590085     A  4680.389142
     NYK    30.523478     B  4901.701010
     SFO    25.589781     A  4731.431501

# Pivot Tables
Pandas provides a function ‘pivot_table’ to create MS-Excel spreadsheet style pivot tables. It can take following arguments:
    * data: DataFrame object,
    * values: column to aggregate,
    * Index: row labels,
    * columns: column labels,
    * aggfunc: aggregation function to be used on values, default is NumPy.mean

In [82]:
# by state and name find mean age for each grade
pd.pivot_table(df, values='Age', index=['State', 'Name'], columns=['Grade'])

Grade               A          B          C
State Name                                 
CA    jane  34.479582        NaN        NaN
NYK   jack        NaN  39.044827  26.487404
      jane        NaN  30.523478        NaN
SFO   jack  30.162886        NaN  26.930186
      jane  25.589781        NaN        NaN