In [4]:
import numpy as np

## random.randint
Return random integers from low (inclusive) to high (exclusive).

In [5]:
x1 = np.random.randint(low=0, high= 10, size=(15, ))
x1

array([9, 9, 9, 6, 6, 6, 0, 5, 3, 9, 9, 8, 3, 9, 4])

## random.uniform
Draw samples from a uniform distribution. Samples are uniformly distributed over the half-open interval [low, high) (includes low, but excludes high).

In other words, any value within the given interval is equally likely to be drawn by uniform.

$p(x) = \frac{1}{b - a}$

In [7]:
x2 = np.random.uniform(low=0, high= 10, size=(15, )).astype(int)
x2

array([3, 8, 6, 6, 7, 0, 4, 6, 5, 6, 0, 0, 2, 4, 4])

## random.choice
Generates a random sample from a given 1-D array

In [9]:
x3 = np.random.choice(a=15, size=4)
x3

array([10,  1,  3,  0])

Generate a uniform random sample from np.arange(5) of size 3 without replacement:

In [10]:
x3 = np.random.choice(a=15, size=4, replace= False)
x3

array([2, 0, 3, 4])

## random.randrange
The randrange() method returns a randomly selected element from the specified range.


random.randrange(start, stop, step)


In [14]:
from random import randrange

x4 = [randrange(5) for i in range(15)]

x4

[1, 4, 4, 4, 1, 2, 4, 3, 2, 1, 2, 4, 4, 1, 1]

## random.randint

random.randint(a, b) returns a random integer N such that a <= N <= b.

Syntax: random.randint(start, stop)

In [16]:
from random import randint
x5 = [randint(0, 5) for i in range(0, 15)]
x5

[2, 3, 5, 5, 5, 1, 2, 2, 0, 3, 1, 2, 0, 0, 1]