In [1]:
import numpy as np

In [2]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
b = a[::-1]
b

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

flatten() always allocates new memory, whereas ravel() might return a view of an array

In [4]:
a.flatten()
b.ravel()

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [5]:
b = np.arange(0, 24).reshape(2, 3, 4)  # (#Depth, r, c)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [6]:
b.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [7]:
b.T.shape

(4, 3, 2)

Stacking arrays Arrays can be stacked horizontally, depth-wise, or vertically. We can use, for that purpose, the vstack(), dstack(), hstack(), column_stack(), row_stack(), and concatenate() functions.

In [25]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
b = 2 * a
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [27]:
np.hstack((a, b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [28]:
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [29]:
np.concatenate((a, b), axis = 0)    # vstack: axis = 0

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [30]:
np.concatenate((a, b), axis = 1)    # hstack: axis = 1

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

Depth stacking: Additionally, there is depth-wise stacking using dstack(), stacking of a list of arrays along the third
axis (depth).

In [31]:
c = np.dstack((a, b))
print(c)
c.shape

[[[ 1  2]
  [ 2  4]
  [ 3  6]]

 [[ 4  8]
  [ 5 10]
  [ 6 12]]

 [[ 7 14]
  [ 8 16]
  [ 9 18]]]


(3, 3, 2)

In [48]:
a3= np.zeros((3, 3), dtype = np.int8)
b3= np.ones((3, 3), dtype = np.int8)
c3= np.full((3, 3), 2, dtype = np.int8)
d3= np.full((3, 3), 3, dtype = np.int8)
print(a3)
print(b3)
print(c3)
print(d3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [49]:
np.dstack((a3, b3, c3, d3))

array([[[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]], dtype=int8)

Column stacking: The column_stack() function stacks one-dimensional arrays column-wise.

In [43]:
a = np.array([0, 1])
b = np.array([2, 3])
a

array([0, 1])

In [44]:
b

array([2, 3])

In [45]:
c = np.column_stack((a, b))
print(c)

[[0 2]
 [1 3]]


In [47]:
d= np.row_stack((a, b))
d

array([[0, 1],
       [2, 3]])

In [51]:
z = np.row_stack((a3, b3, c3, d3))
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int8)

## row_stack == vstack

### Splitting arrays: 
Arrays can be split vertically, horizontally, or depth-wise. The functions involved are hsplit(), vsplit(), dsplit(), and split().

In [53]:
a = np.arange(0, 9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
a_splitted = np.split(a, 3)
a_splitted

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [58]:
a_split_r = np.split(a, 3, axis = 0)  #  vsplit
a_split_r

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [56]:
a_split_c = np.split(a, 3, axis = 1)  #  hsplit
a_split_c

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [60]:
c= np.arange(27).reshape(3, 3, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [62]:
np.dsplit(c, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]),
 array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

____

### Array attributes:
shape, ndim, size, itemsize, nbytes

#### Converting arrays
tolist(), astype

_____
### The resize method works just like the reshape method, but modifies the array it operates on:

b.resize((2,12))

____
## identity matrix

In [64]:
i3 = np.eye(3)
i3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

_____

In [2]:
a = np.arange(10)    #  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.arange(10, 20)    #  array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [3]:
c = []
for i in range(len(a)):
    a[i] = i **2
    b[i] = i **3
    c.append(a[i] + b[i])
c

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]