In [1]:
import numpy as np
import sys

In [2]:
# create an array with 10^7 elements
arr = np.arange(1e7)
arr

array([0.000000e+00, 1.000000e+00, 2.000000e+00, ..., 9.999997e+06,
       9.999998e+06, 9.999999e+06])

In [4]:
arr.shape

(10000000,)

In [5]:
arr.ndim

1

In [8]:
# converting ndarray to lsit
larr = arr.tolist()
# larr

### Array Creation and Data Typing: np.array, np.zeros, np.arange, np.linspace, np.logspace, dtype, astype

In [3]:
a = np.linspace(0, 1, 100).astype(np.float16)
a

array([0.    , 0.0101, 0.0202, 0.0303, 0.0404, 0.0505, 0.0606, 0.0707,
       0.0808, 0.0909, 0.101 , 0.1111, 0.1212, 0.1313, 0.1414, 0.1515,
       0.1616, 0.1718, 0.1818, 0.1919, 0.202 , 0.2122, 0.2222, 0.2323,
       0.2424, 0.2524, 0.2627, 0.2727, 0.2827, 0.293 , 0.303 , 0.3132,
       0.3232, 0.3333, 0.3435, 0.3535, 0.3635, 0.3738, 0.3838, 0.394 ,
       0.404 , 0.414 , 0.4243, 0.4343, 0.4443, 0.4546, 0.4646, 0.4749,
       0.4849, 0.4949, 0.505 , 0.515 , 0.5254, 0.535 , 0.5454, 0.5557,
       0.5654, 0.5757, 0.586 , 0.596 , 0.606 , 0.616 , 0.6265, 0.636 ,
       0.6465, 0.6567, 0.6665, 0.677 , 0.687 , 0.697 , 0.707 , 0.7173,
       0.727 , 0.7373, 0.7476, 0.758 , 0.7676, 0.778 , 0.788 , 0.798 ,
       0.808 , 0.8184, 0.828 , 0.8384, 0.8486, 0.8584, 0.8687, 0.879 ,
       0.8887, 0.899 , 0.909 , 0.9194, 0.929 , 0.9395, 0.9497, 0.9595,
       0.9697, 0.98  , 0.9897, 1.    ], dtype=float16)

In [5]:
# generate an array from 1 to 10 # in log10 space in 100 steps
b = np.logspace(0, 1, 100, base= 10)
b

array([ 1.        ,  1.02353102,  1.04761575,  1.07226722,  1.09749877,
        1.12332403,  1.149757  ,  1.17681195,  1.20450354,  1.23284674,
        1.26185688,  1.29154967,  1.32194115,  1.35304777,  1.38488637,
        1.41747416,  1.45082878,  1.48496826,  1.51991108,  1.55567614,
        1.59228279,  1.62975083,  1.66810054,  1.70735265,  1.7475284 ,
        1.78864953,  1.83073828,  1.87381742,  1.91791026,  1.96304065,
        2.009233  ,  2.05651231,  2.10490414,  2.15443469,  2.20513074,
        2.25701972,  2.3101297 ,  2.36448941,  2.42012826,  2.47707636,
        2.53536449,  2.59502421,  2.65608778,  2.71858824,  2.7825594 ,
        2.84803587,  2.91505306,  2.98364724,  3.05385551,  3.12571585,
        3.19926714,  3.27454916,  3.35160265,  3.43046929,  3.51119173,
        3.59381366,  3.67837977,  3.76493581,  3.85352859,  3.94420606,
        4.03701726,  4.1320124 ,  4.22924287,  4.32876128,  4.43062146,
        4.53487851,  4.64158883,  4.75081016,  4.86260158,  4.97

In [9]:
arr1d = np.arange(1000)
arr3d = arr1d.reshape(10, 10, 10)

In [10]:
arr4d = np.zeros((10, 10, 10, 10))

In [12]:
 # Inversely, we can flatten arrays
arr4d.ravel()
print(arr1d.shape)
print(arr4d.shape)

(1000,)
(10, 10, 10, 10)


In [ ]:
# create a 100-element array with random values from standard normal distribution (Gaussian distribution) sigma=1, mean=0

In [5]:
a = np.random.randn(100)  # anp ndarray with shape of (100, 0)

In [6]:
index= a > 0.2
b = a[index]    # extract some elements
b

array([0.75730032, 1.07838768, 0.35275228, 0.49104486, 0.77979982,
       0.72076138, 0.49462479, 0.91183041, 0.86314427, 0.61679063,
       1.22689179, 1.97101512, 0.99093739, 0.53596934, 0.52708209,
       0.74770233, 1.00362755, 1.104705  , 0.73589991, 0.31893356,
       0.53924909, 0.33987522, 0.46755449, 0.57046981, 0.84729592,
       1.40497021, 1.12184692, 0.78191418, 0.75911089, 0.50024785,
       1.68572181, 1.77815168, 0.85744835, 1.01745687, 0.73621516,
       1.01182761, 1.36785899, 0.38853605, 1.39648006, 1.1869768 ,
       0.40912747, 1.01367117, 0.2636897 , 0.2256965 , 1.87162703,
       1.12252029, 0.94655006, 1.207317  , 0.99729015])

In [8]:
b = (b ** 2) + 2    #  execute some operation
b

array([4.03489148, 2.70070293, 5.51774718, 5.09364107, 3.9374197 ,
       4.19188922, 5.08124068, 3.36554489, 3.57497976, 4.62300478,
       2.24476424, 5.55285023, 3.03641171, 4.93346756, 4.96591936,
       4.0763116 , 2.98551632, 2.60781805, 4.12708026, 5.60347221,
       4.92140025, 5.55128308, 5.17336031, 4.80416526, 3.64375379,
       2.00067906, 2.54976218, 3.92823835, 4.02706592, 5.06163237,
       2.70838823, 3.34983364, 3.59967432, 2.93080338, 4.1257268 ,
       2.95297599, 2.01663114, 5.41894796, 2.00248437, 2.34938274,
       5.3584767 , 2.94569936, 5.72670571, 5.79883912, 4.25897213,
       2.54752333, 3.21891091, 2.29418221, 3.010854  ])

In [10]:
a[index] = b  #  put back the modified elements
a

array([ 4.03489148,  2.70070293, -0.82916546,  5.51774718, -1.65337568,
       -0.60745323, -1.31295613,  5.09364107, -0.87127516,  3.9374197 ,
       -0.87100475,  4.19188922,  5.08124068,  3.36554489, -2.1171383 ,
        3.57497976, -0.17796029, -1.86846966, -0.07931709, -0.51367314,
        4.62300478,  0.11674007,  2.24476424,  5.55285023, -1.08747717,
        3.03641171,  4.93346756,  0.00753873, -0.38391767,  4.96591936,
        4.0763116 ,  2.98551632,  2.60781805,  4.12708026, -0.36888534,
       -0.37126957,  5.60347221,  4.92140025,  5.55128308, -1.29141198,
       -1.15612004, -0.15586548,  5.17336031, -0.39231806,  0.10609292,
       -0.71173534,  4.80416526,  3.64375379,  2.00067906, -0.46735435,
        2.54976218, -1.4580978 , -1.09240242,  3.92823835,  0.14231511,
       -0.18094151,  4.02706592, -0.32328322,  5.06163237, -0.55546894,
        2.70838823,  3.34983364,  3.59967432, -0.15941361,  2.93080338,
        4.1257268 , -1.83279909, -0.56971362,  2.95297599, -0.86

In [ ]:
np.save('a.npy', a)
np.savez('a.npyz', a)    # if space is the issue for latge files, use np.savez instead

## linear Algebra
$AX = B$ &rarr; X = $A^{-1}B$

In [11]:
# defining matrices
A = np.matrix([[3, 6, -5], [1, -3, 2], [5, -1, 4]])

B = np.matrix([[12], [-2], [10]])

A

matrix([[ 3,  6, -5],
        [ 1, -3,  2],
        [ 5, -1,  4]])

In [13]:
B

matrix([[12],
        [-2],
        [10]])

In [15]:
# solving for the variables, where we invert A
X = (A ** (-1)) * B
X

matrix([[1.75],
        [1.75],
        [0.75]])

$x$ = 1.75, $y$ = 1.75, and $z$ = 0.75

_____

In [16]:
a = np.array([[3, 6, -5],
[1, -3, 2],
[5, -1, 4]])

# Defining the array
b = np.array([12, -2, 10])

In [17]:
# Soling for the variables, where we invert A
x= np.linalg.inv(a).dot(b)
x

array([1.75, 1.75, 0.75])

## Scipy
The optimization package in SciPy allows us to solve minimization problems easily and quickly

In [1]:
# linear regression
import numpy as np
from scipy.optimize import curve_fit

In [3]:
# create a function to model and create data
def func(x, a, b):
    return a *x + b

# generating clean data 
x= np.linspace(0, 10, 100)  # an array of 100 elements between 0 to 10
y= func(x, 1, 2)    # an array of 100 elements generated from x, a, b

# adding noise to the data
yn = y + 0.9 * np.random.normal(size = (len(x)))    # an array of 100 elements

In [8]:
# executing curve_fir on noisy data
ppt, pcov = curve_fit(func, x, yn)